include: package:flutter_lints/flutter.yaml

linter:
    rules:
        # Add your custom lint rules here
        # For example:
        # - always_declare_return_types
        # - avoid_print

analyzer:
    errors:
        non_constant_identifier_names: ignore
    plugins:
        - custom_lint
